baseURL = "https://danielabrozzoni.com/"
languageCode = "en-us"
title = "Daniela Brozzoni"
theme = "mini"

[params]
mainSection = "posts"
math = true # just in case, you know...
enableRss = true

[social]
github = "https://github.com/danielabrozzoni"
twitter = "https://twitter.com/danielabrozzoni"
