baseURL = "https://danielabrozzoni.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Daniela Brozzoni"
theme = "fuji"

hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 10

[params]
author = "Daniela Brozzoni"                # You can also set author in post front matter individually
subTitle = ""
defaultTheme = "auto"              # default theme when first visit (auto|dark|light)

# Source URL of the website, will appear in the footer
sourceURL = "https://github.com/danielabrozzoni/danielabrozzoni.com"

# Word counter and read time indicator in post metadata
showWordCounter = true
showReadTime = true

# License in the footer
showLicenseInFooter = false

# License at the end of each post
showLicense = false
showToc = false

# Copyright
copyrightStartYear = "2020"

# Open Graph & Twitter Card variables
# You can also set description and images in post front matter individually
description = ""
og = "/images/avatar.png"

# Posts shown in homepage
mainSections = ["posts"]

# custom lazyload placeholder
# 16:9
lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
# 32:9
lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
# 8:9
lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

# Let images display in full brightness under dark mode
disableDarkImage = true

[permalinks]
post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = false # Disable Hugo's code highlighter

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = "tags"

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[[menu.nav]]
name = "About"
url = "/about/"
weight = 2
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 3

[[menu.link]]
name = "GitHub"
url = "https://github.com/danielabrozzoni"
weight = 1
[[menu.link]]
name = "Twitter"
url = "https://twitter.com/danielabrozzoni"
weight = 2

[build]
noJSConfigInAssets = true

[security]
enableInlineShortcodes = true
